version: '3'
volumes:
  k3s-server: {}
  k3s-agent: {}
services:
  server:
    hostname: k3s-master-1
    restart: always
    image: "gcr.io/its-artifact-commons/k3s:develop-bc50c85"
    command:
    - server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=secret
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
      - .:/output
      - k3s-server:/var/lib/rancher/k3s
    ports:
    - 6443:6443

  agent:
    hostname: k3s-worker-1
    restart: always
    image: "gcr.io/its-artifact-commons/k3s:develop-bc50c85"
    command:
    - agent
    tmpfs:
    - /run
    - /var/run
    privileged: true
    volumes:
      - k3s-agent:/etc/rancher/node #This is where agent stroe server password
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=secret
